package com.chinasoft.app.hibernatejboss;

// Generated 2017-7-14 15:24:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer courseid;
	private String coursename;
	private Set stuandcous = new HashSet(0);

	public Course() {
	}

	public Course(String coursename, Set stuandcous) {
		this.coursename = coursename;
		this.stuandcous = stuandcous;
	}

	public Integer getCourseid() {
		return this.courseid;
	}

	public void setCourseid(Integer courseid) {
		this.courseid = courseid;
	}

	public String getCoursename() {
		return this.coursename;
	}

	public void setCoursename(String coursename) {
		this.coursename = coursename;
	}

	public Set getStuandcous() {
		return this.stuandcous;
	}

	public void setStuandcous(Set stuandcous) {
		this.stuandcous = stuandcous;
	}

}
