package com.chinasoft.app.hibernatejboss;

// Generated 2017-7-14 15:24:45 by Hibernate Tools 3.4.0.CR1

/**
 * StuandcouId generated by hbm2java
 */
public class StuandcouId implements java.io.Serializable {

	private Integer courseid;
	private Integer sid;

	public StuandcouId() {
	}

	public StuandcouId(Integer courseid, Integer sid) {
		this.courseid = courseid;
		this.sid = sid;
	}

	public Integer getCourseid() {
		return this.courseid;
	}

	public void setCourseid(Integer courseid) {
		this.courseid = courseid;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StuandcouId))
			return false;
		StuandcouId castOther = (StuandcouId) other;

		return ((this.getCourseid() == castOther.getCourseid()) || (this
				.getCourseid() != null && castOther.getCourseid() != null && this
				.getCourseid().equals(castOther.getCourseid())))
				&& ((this.getSid() == castOther.getSid()) || (this.getSid() != null
						&& castOther.getSid() != null && this.getSid().equals(
						castOther.getSid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCourseid() == null ? 0 : this.getCourseid().hashCode());
		result = 37 * result
				+ (getSid() == null ? 0 : this.getSid().hashCode());
		return result;
	}

}
