package com.courseratingsystem.web.domain;

// Generated 2017-7-18 12:25:34 by Hibernate Tools 3.4.0.CR1

/**
 * Coursemark generated by hbm2java
 */
public class Coursemark implements java.io.Serializable {

	private int courseid;
	private Integer averageRatingsUsefulness;
	private Integer averageRatingsVividness;
	private Integer averageRatingsSpareTimeOccupation;
	private Integer averageRatingsScoring;
	private Integer averageRatingsRollCall;
	private Integer peopleCount;
	private Integer recommendationScore;
	private Integer finalType;

	public Coursemark() {
	}

	public Coursemark(int courseid) {
		this.courseid = courseid;
	}

	public Coursemark(int courseid, Integer averageRatingsUsefulness,
			Integer averageRatingsVividness,
			Integer averageRatingsSpareTimeOccupation,
			Integer averageRatingsScoring, Integer averageRatingsRollCall,
			Integer peopleCount, Integer recommendationScore, Integer finalType) {
		this.courseid = courseid;
		this.averageRatingsUsefulness = averageRatingsUsefulness;
		this.averageRatingsVividness = averageRatingsVividness;
		this.averageRatingsSpareTimeOccupation = averageRatingsSpareTimeOccupation;
		this.averageRatingsScoring = averageRatingsScoring;
		this.averageRatingsRollCall = averageRatingsRollCall;
		this.peopleCount = peopleCount;
		this.recommendationScore = recommendationScore;
		this.finalType = finalType;
	}

	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

	public Integer getAverageRatingsUsefulness() {
		return this.averageRatingsUsefulness;
	}

	public void setAverageRatingsUsefulness(Integer averageRatingsUsefulness) {
		this.averageRatingsUsefulness = averageRatingsUsefulness;
	}

	public Integer getAverageRatingsVividness() {
		return this.averageRatingsVividness;
	}

	public void setAverageRatingsVividness(Integer averageRatingsVividness) {
		this.averageRatingsVividness = averageRatingsVividness;
	}

	public Integer getAverageRatingsSpareTimeOccupation() {
		return this.averageRatingsSpareTimeOccupation;
	}

	public void setAverageRatingsSpareTimeOccupation(
			Integer averageRatingsSpareTimeOccupation) {
		this.averageRatingsSpareTimeOccupation = averageRatingsSpareTimeOccupation;
	}

	public Integer getAverageRatingsScoring() {
		return this.averageRatingsScoring;
	}

	public void setAverageRatingsScoring(Integer averageRatingsScoring) {
		this.averageRatingsScoring = averageRatingsScoring;
	}

	public Integer getAverageRatingsRollCall() {
		return this.averageRatingsRollCall;
	}

	public void setAverageRatingsRollCall(Integer averageRatingsRollCall) {
		this.averageRatingsRollCall = averageRatingsRollCall;
	}

	public Integer getPeopleCount() {
		return this.peopleCount;
	}

	public void setPeopleCount(Integer peopleCount) {
		this.peopleCount = peopleCount;
	}

	public Integer getRecommendationScore() {
		return this.recommendationScore;
	}

	public void setRecommendationScore(Integer recommendationScore) {
		this.recommendationScore = recommendationScore;
	}

	public Integer getFinalType() {
		return this.finalType;
	}

	public void setFinalType(Integer finalType) {
		this.finalType = finalType;
	}

}
