package com.courseratingsystem.web.domain;

// Generated 2017-7-18 14:18:31 by Hibernate Tools 3.4.0.CR1

/**
 * Coursemark generated by hbm2java
 */
public class Coursemark implements java.io.Serializable {

	private int courseid;
	private Course course;
	private Float averageRatingsUsefulness;
	private Float averageRatingsVividness;
	private Float averageRatingsSpareTimeOccupation;
	private Float averageRatingsScoring;
	private Float averageRatingsRollCall;
	private Integer peopleCount;
	private Float recommendationScore;
	private Integer finalType;

	public Coursemark() {
	}

	public Coursemark(Course course) {
		this.course = course;
	}

	public Coursemark(Course course, Float averageRatingsUsefulness,
			Float averageRatingsVividness,
			Float averageRatingsSpareTimeOccupation,
			Float averageRatingsScoring, Float averageRatingsRollCall,
			Integer peopleCount, Float recommendationScore, Integer finalType) {
		this.course = course;
		this.averageRatingsUsefulness = averageRatingsUsefulness;
		this.averageRatingsVividness = averageRatingsVividness;
		this.averageRatingsSpareTimeOccupation = averageRatingsSpareTimeOccupation;
		this.averageRatingsScoring = averageRatingsScoring;
		this.averageRatingsRollCall = averageRatingsRollCall;
		this.peopleCount = peopleCount;
		this.recommendationScore = recommendationScore;
		this.finalType = finalType;
	}

	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Float getAverageRatingsUsefulness() {
		return this.averageRatingsUsefulness;
	}

	public void setAverageRatingsUsefulness(Float averageRatingsUsefulness) {
		this.averageRatingsUsefulness = averageRatingsUsefulness;
	}

	public Float getAverageRatingsVividness() {
		return this.averageRatingsVividness;
	}

	public void setAverageRatingsVividness(Float averageRatingsVividness) {
		this.averageRatingsVividness = averageRatingsVividness;
	}

	public Float getAverageRatingsSpareTimeOccupation() {
		return this.averageRatingsSpareTimeOccupation;
	}

	public void setAverageRatingsSpareTimeOccupation(
			Float averageRatingsSpareTimeOccupation) {
		this.averageRatingsSpareTimeOccupation = averageRatingsSpareTimeOccupation;
	}

	public Float getAverageRatingsScoring() {
		return this.averageRatingsScoring;
	}

	public void setAverageRatingsScoring(Float averageRatingsScoring) {
		this.averageRatingsScoring = averageRatingsScoring;
	}

	public Float getAverageRatingsRollCall() {
		return this.averageRatingsRollCall;
	}

	public void setAverageRatingsRollCall(Float averageRatingsRollCall) {
		this.averageRatingsRollCall = averageRatingsRollCall;
	}

	public Integer getPeopleCount() {
		return this.peopleCount;
	}

	public void setPeopleCount(Integer peopleCount) {
		this.peopleCount = peopleCount;
	}

	public Float getRecommendationScore() {
		return this.recommendationScore;
	}

	public void setRecommendationScore(Float recommendationScore) {
		this.recommendationScore = recommendationScore;
	}

	public Integer getFinalType() {
		return this.finalType;
	}

	public void setFinalType(Integer finalType) {
		this.finalType = finalType;
	}

}
