package com.courseratingsystem.web.domain;

// Generated 2017-7-18 12:25:34 by Hibernate Tools 3.4.0.CR1

/**
 * Logininfo generated by hbm2java
 */
public class Logininfo implements java.io.Serializable {

	private Integer credentialsid;
	private User user;
	private String username;
	private String password;

	public Logininfo() {
	}

	public Logininfo(User user, String username, String password) {
		this.user = user;
		this.username = username;
		this.password = password;
	}

	public Integer getCredentialsid() {
		return this.credentialsid;
	}

	public void setCredentialsid(Integer credentialsid) {
		this.credentialsid = credentialsid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
