package com.courseratingsystem.web.domain;

// Generated 2017-7-18 12:25:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer teacherid;
	private String teachername;
	private Set comments = new HashSet(0);
	private Set courses = new HashSet(0);

	public Teacher() {
	}

	public Teacher(String teachername, Set comments, Set courses) {
		this.teachername = teachername;
		this.comments = comments;
		this.courses = courses;
	}

	public Integer getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(Integer teacherid) {
		this.teacherid = teacherid;
	}

	public String getTeachername() {
		return this.teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
