package com.courseratingsystem.web.domain;

// Generated 2017-7-18 12:25:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userid;
	private String nickname;
	private String grade;
	private Set courses = new HashSet(0);
	private Set logininfos = new HashSet(0);
	private Set comments = new HashSet(0);

	public User() {
	}

	public User(String nickname, String grade, Set courses, Set logininfos,
			Set comments) {
		this.nickname = nickname;
		this.grade = grade;
		this.courses = courses;
		this.logininfos = logininfos;
		this.comments = comments;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	public Set getLogininfos() {
		return this.logininfos;
	}

	public void setLogininfos(Set logininfos) {
		this.logininfos = logininfos;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
