package com.chinasoft.app.hibernatejboss;

// Generated 2017-7-14 15:24:45 by Hibernate Tools 3.4.0.CR1

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer bookid;
	private String bookname;
	private Long bookprice;

	public Book() {
	}

	public Book(String bookname, Long bookprice) {
		this.bookname = bookname;
		this.bookprice = bookprice;
	}

	public Integer getBookid() {
		return this.bookid;
	}

	public void setBookid(Integer bookid) {
		this.bookid = bookid;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public Long getBookprice() {
		return this.bookprice;
	}

	public void setBookprice(Long bookprice) {
		this.bookprice = bookprice;
	}

}
