package com.chinasoft.app.hibernatejboss;

// Generated 2017-7-14 15:24:45 by Hibernate Tools 3.4.0.CR1

/**
 * Stuandcou generated by hbm2java
 */
public class Stuandcou implements java.io.Serializable {

	private StuandcouId id;
	private Student student;
	private Course course;

	public Stuandcou() {
	}

	public Stuandcou(StuandcouId id) {
		this.id = id;
	}

	public Stuandcou(StuandcouId id, Student student, Course course) {
		this.id = id;
		this.student = student;
		this.course = course;
	}

	public StuandcouId getId() {
		return this.id;
	}

	public void setId(StuandcouId id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

}
