package com.chinasoft.app.hibernatejboss;

// Generated 2017-7-14 15:24:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private Classinfor classinfor;
	private String sname;
	private Set stuandcous = new HashSet(0);

	public Student() {
	}

	public Student(Classinfor classinfor, String sname, Set stuandcous) {
		this.classinfor = classinfor;
		this.sname = sname;
		this.stuandcous = stuandcous;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Classinfor getClassinfor() {
		return this.classinfor;
	}

	public void setClassinfor(Classinfor classinfor) {
		this.classinfor = classinfor;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Set getStuandcous() {
		return this.stuandcous;
	}

	public void setStuandcous(Set stuandcous) {
		this.stuandcous = stuandcous;
	}

}
